- include_tasks: check_box_tasks.yml
- name: ToDo skript is often here. Could be better
  make:
    chdir: ./
    target: no-cloud

- name: Create Vagrantfile for {{BASE}}
  template:
    dest: Vagrantfile-{{BASE}}
    src: ansible/Vagrantfile-ubuntu_1804_de.j2

- name: build {{BASE}}
  # Use BASE NOT box_name! The name box_name is double.
  shell: >
    packer build -force
    -var "box_name={{BASE}}"
    -var "box_organization={{box_organization}}"
    -var "requirements={{requirements}}"
    -var "playbook={{playbook}}"
    packer-ubuntu_1804_de-no-cloud.json
  args:
    executable: /bin/bash
    chdir: ./
  environment:
    PACKER_LOG: 1
    PACKER_LOG_PATH: ./packer.log
