- name: "build: Start build info"
  debug:
    msg: Build Box {{BASE}} depends on {{box_developer}}/{{box_lts}} in version {{box_version}}
    verbosity: 1

- include_tasks: check_box_tasks.yml

- name: "build: ToDo skript is often here. Could be better"
  make:
    chdir: ./
    target: no-cloud

- name: "build: Ensure builds directory vor {{BASE}} exists"
  file:
    path: "builds/{{BASE}}"
    state: directory

- name: "build: Create builds Vagrantfile-{{BASE}}"
  vars:
    BUILD_PATH: "{{foo.vagrant_path}}"
  template:
    dest: "{{foo.dest}}/Vagrantfile-{{BASE}}"
    src: templates/Vagrantfile-ubuntu_1804_de.j2
  # ToDo loop_control set for outer_loop
  loop_control:
    loop_var: foo
  with_items:
    - vagrant_path: "builds/"
      dest: "builds-config"
    - vagrant_path: ""
      dest: "builds"

- block:
  - name: "build: build {{BASE}}"
    # Use BASE NOT box_name! The name box_name is double.
    shell: >
      packer build -force
      -var "box_name={{BASE}}"
      -var "box_organization={{box_organization}}"
      -var "requirements={{requirements}}"
      -var "playbook={{playbook}}"
      packer-ubuntu_1804_de-no-cloud.json
    args:
      executable: /bin/bash
      chdir: ./
    environment:
      PACKER_LOG: 1
      PACKER_LOG_PATH: ./log/packer.log
  rescue:
  - name: Error debug info
    debug:
      msg: Build Box {{BASE}} error depends on {{box_developer}}/{{box_lts}} in version {{box_version}}
  - command: /bin/false
