---
  - hosts: localhost
    # connection: local
    gather_facts: yes

    tasks:
      - name: "build: Include variables"
        include_vars: ubuntu_1804.yml

      - name: "build: Create virtualbox-ubuntu_1804_xy"
        debug:
          var: "{{item}}"
          verbosity: 1
        with_items: "{{ubuntu_1804}}"

      - name: "build: Ensure directories exists"
        file:
          path: "{{item}}"
          state: directory
        with_items:
          - builds
          - builds-config

      - name: "build: Ensure builds-config/version exists"
        file:
          path: builds-config/version
          state: touch

      - name: "build: Ensure builds-config/version for pre_box exists"
        file:
          path: "builds-config/version-{{item.dependencies.box_lts}}"
          state: touch
        with_items:
          - "{{ubuntu_1804[BASE_NAME]}}"

      - debug:
          msg: "{{ubuntu_1804[BASE_NAME]}}"
          verbosity: 0

      - include_tasks: build-tasks.yml
        BASE: "ubuntu_1804_{{outer_item.name}}"
        box_developer: "{{outer_item.dependencies.box_developer}}"
        box_organization: "{{outer_item.box_organization | default ('kraeml')}}"
        box_lts: "{{outer_item.dependencies.box_lts}}"
        box_version: "{{outer_item.dependencies.box_version | default (lookup('file', 'builds-config/version-{{box_lts}}'))}}"
        box_name: "{{box_organization}}/ubuntu_1804_{{outer_item.name}}"
        requirements: "ansible/{{outer_item.dependencies.requirements}}"
        playbook: "ansible/{{outer_item.dependencies.playbook}}"
        # Used later in box_ovf_path
        box_ovf_default: "{{ovf_path}}file:-VAGRANTSLASH--VAGRANTSLASH-builds-VAGRANTSLASH-virtualbox-{{outer_item.dependencies.box_lts}}.box/0/virtualbox/"
        box_ovf_path: "{{outer_item.dependencies.box_ovf_path | default (box_ovf_default)}}"
        with_items:
          - "{{ubuntu_1804[BASE_NAME]}}"
        loop_control:
          loop_var: outer_item
        #environment:
        #  http_proxy: "{{ansible_default_ipv4.address}}:8888"
