---
- hosts: localhost
  vars:
    box_developer: "geerlingguy"
    box_lts: "ubuntu1804"
    box_name: "{{box_developer}}/{{box_lts}}"
    box_version: "1.0.1"
    box_ovf_path: "{{ansible_user_dir}}/.vagrant.d/boxes/{{box_developer}}-VAGRANTSLASH-{{box_lts}}/{{box_version}}/virtualbox/"
    s3_bucket_name: "kraeml-vagrant-boxen"
    region: "eu-central-1"
  pre_tasks:
    - name: Create s3 bucket
      s3_bucket:
        name: "{{s3_bucket_name}}"
        region: "{{aws_region}}"
        versioning: yes
        #aws_access_key: "{{aws_access_key}}"
        #aws_secret_key: "{{aws_secret_key}}"
      register: s3_url

    - name: Display s3 url
      debug: var=s3_url
      
  tasks:
    - name: "Check box {{box_name}} is in version {{box_version}}"
      command: "vagrant box add --box-version {{box_version}} {{box_name}}"
      register: box_info
      ignore_errors: yes
      changed_when: False

    - name: "Display box info"
      debug:
        var: box_info
        verbosity: 2

    - name: "Display box path"
      debug:
        var: box_ovf_path
        verbosity: 2

    - name: "Test box exists"
      command: "ls -ld {{box_ovf_path}}"
      args:
        creates: "{{box_ovf_path}}"

    - name: Ensure virtualbox-ovf directory exists
      file:
        path: ./virtualbox-ovf
        state: directory

    - name: "Copy virtualbox files"
      copy:
        dest: ./virtualbox-ovf
        src: "{{box_ovf_path}}"
