---
  - hosts: all
    roles:
    - role: gantsign.xdesktop
      become: yes
    - role: gantsign.lightdm
      become: yes
      lightdm_autologin_user: vagrant
      tags:
        - desktop

    tasks:
    - name: Autologin for {{ansible_user_id}}
      become: yes
      blockinfile:
        path: /etc/gdm3/custom.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        insertafter: "# Enabling automatic login"
        block: |
          AutomaticLoginEnable = true
          AutomaticLogin = {{ansible_user_id}}
