---
- src: https://github.com/gantsign/ansible-role-xdesktop/archive/2.3.0.tar.gz
  name: gantsign.xdesktop
- src: gantsign.lightdm
- src: geerlingguy.mysql
- src: geerlingguy.nginx
- src: geerlingguy.php
- src: https://github.com/geerlingguy/ansible-role-php-versions/archive/2.1.3.tar.gz
  name: geerlingguy.php-versions
- src: geerlingguy.php-mysql
- src: geerlingguy.nodejs
#- src: fubarhouse.nodejs
