---
- hosts: all
  #become: yes
  gather_facts: yes
  roles:
    - role: oefenweb.locales
      become: yes
      locales_present:
        - en_US.UTF-8
        - de_DE.UTF-8
      locales_language_packs_present:
        - language-pack-en
        - language-pack-en-base
        - language-pack-de
        - language-pack-de-base
      locales_default:
        lang: de_DE.UTF-8
        # language: de_DE.UTF-8
      tags:
        - locale_de
    - role: oefenweb.timezone
      become: yes
      timezone_zone: "Europe/Berlin"
      tags:
        - locale_de
    - role: gantsign.keyboard
      become: yes
      keyboard_model: pc105
      keyboard_layout: de
      tags:
        - locale_de

  tasks:
    - name: "Install german packages"
      become: yes
      apt:
        name: "{{item}}"
      with_items:
        - manpages-de
    - block:
      - name: "Create tuxcademy user(s)"
        become: yes
        user:
          name: "{{item.name}}"
          shell: /bin/bash
          comment: "Tuxcademy user"
          uid: "{{item.uid}}"
        with_items:
          - name: hugo
            uid: 5000
      - name: "Create tuxcademy files"
        become: yes
        file:
          path: /home/hugo/datei.txt
          state: touch
          owner: "{{ansible_user_id}}"
          group: "{{ansible_user_gid}}"
