---
- hosts: all
  #become: yes

  gather_facts: yes

  #roles:
    #- role: ThorstenS-linux.packer-io
    #  become: yes
    #  packer_version: 1.4.5
    #  tags:
    #    - packer
  tasks:
    - name: Say somthing
      debug:
        msg: Hello SA
